name: LaTeX-compile

# run automaticamente quando si fa push, compare nella lista degli workflow nelle actions della repo
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: pkg-install
        run: |
          sudo apt-get --fix-missing update
          sudo apt-get --fix-missing install texlive-full asymptote latexmk
        # sudo apt-get upgrade
      - name: compile
        run: sudo latexmk --pdf MateBase.tex
